llm_groq:
  model: 'llama3-70B-8192'
  api_key: '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'
  temperature: 0.2
  max_tokens: 2048
  timeout: 10

qdrant:
  url: 'https://ea12ed04-6fbb-4e43-b39f-89e22f4d0c9b.europe-west3-0.gcp.cloud.qdrant.io:6333'
  api_key: 'codO4umI5wGOGswv7zcPCUt723Bk3KyIPMZo7lvM0vUSWedQUB6YCQ'
  collection_name: 'phone_production'
  dense_embedding: 'BAAI/bge-small-en-v1.5'
  sparse_embedding: 'Qdrant/bm25'
  late_interaction_embedding: 'colbert-ir/colbertv2.0'
  batch_size: 2
  thresh_score: 0.3

huggingface:
  api_key: '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'
  baai_embedding: 'BAAI/bge-small-en-v1.5'

chroma:
  db_path : 'database'
  collection: 'production'
  top_k: 10
  score_threshold: 0.4

data:
  final_data_path: data/final.csv